"""add_sample_activities_table

Revision ID: 18ba05ddba97
Revises: 8136a8c29d66
Create Date: 2025-11-22 13:49:03.998947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ba05ddba97'
down_revision: Union[str, Sequence[str], None] = '8136a8c29d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_activities_id'), 'sample_activities', ['id'], unique=False)
    op.create_index(op.f('ix_sample_activities_sample_id'), 'sample_activities', ['sample_id'], unique=False)
    op.create_index(op.f('ix_sample_activities_user_id'), 'sample_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_activities_user_id'), table_name='sample_activities')
    op.drop_index(op.f('ix_sample_activities_sample_id'), table_name='sample_activities')
    op.drop_index(op.f('ix_sample_activities_id'), table_name='sample_activities')
    op.drop_table('sample_activities')
    # ### end Alembic commands ###
