"""add customer_id and email_templates table

Revision ID: 9a559acfb9ad
Revises: e51ddd2551f2
Create Date: 2025-11-22 11:27:23.638946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a559acfb9ad'
down_revision: Union[str, Sequence[str], None] = 'e51ddd2551f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    existing_tables = inspector.get_table_names()
    
    # Create email_templates table if it doesn't exist
    if 'email_templates' not in existing_tables:
        op.create_table('email_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('subject', sa.String(length=255), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
        op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=True)
    else:
        # Table exists, just ensure indexes exist
        try:
            op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
        except:
            pass
        try:
            op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=True)
        except:
            pass
    
    # Check if customer_id column exists
    inspector = inspect(connection)
    customers_columns = [col['name'] for col in inspector.get_columns('customers')]
    
    if 'customer_id' not in customers_columns:
        # Add customer_id column as nullable first
        op.add_column('customers', sa.Column('customer_id', sa.String(length=5), nullable=True))
        
        # Generate customer_ids for existing customers
        import random
        import string
        from sqlalchemy import text
        
        result = connection.execute(text("SELECT id FROM customers WHERE customer_id IS NULL"))
        existing_customers = result.fetchall()
        
        for (customer_id_db,) in existing_customers:
            # Generate unique 5-character ID
            while True:
                new_customer_id = ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))
                check = connection.execute(
                    text("SELECT COUNT(*) FROM customers WHERE customer_id = :cid"),
                    {"cid": new_customer_id}
                )
                if check.scalar() == 0:
                    connection.execute(
                        text("UPDATE customers SET customer_id = :cid WHERE id = :id"),
                        {"cid": new_customer_id, "id": customer_id_db}
                    )
                    connection.commit()
                    break
        
        # Now make it non-nullable - MySQL requires existing type
        op.alter_column('customers', 'customer_id',
                        existing_type=sa.String(length=5),
                        nullable=False)
    
    # Create index if it doesn't exist
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('customers')]
    if 'ix_customers_customer_id' not in existing_indexes:
        op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_column('customers', 'customer_id')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
