"""add_reports_table

Revision ID: b76999699945
Revises: 5d0388a06c32
Create Date: 2025-11-24 20:12:00.459367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76999699945'
down_revision: Union[str, Sequence[str], None] = '5d0388a06c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_entry_id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'VALIDATED', 'FINALIZED', name='reportstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('amended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amended_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by_id', sa.Integer(), nullable=True),
    sa.Column('report_data', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amended_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_entry_id'], ['result_entries.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_fingerprint'), 'reports', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_reports_generated_by_id'), 'reports', ['generated_by_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_number'), 'reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_reports_result_entry_id'), 'reports', ['result_entry_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_result_entry_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_number'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_by_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_fingerprint'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
