"""add_view_key_to_reports

Revision ID: ef16e4fd1d9a
Revises: b76999699945
Create Date: 2025-11-24 21:29:36.594099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef16e4fd1d9a'
down_revision: Union[str, Sequence[str], None] = 'b76999699945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('view_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_reports_view_key'), 'reports', ['view_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_view_key'), table_name='reports')
    op.drop_column('reports', 'view_key')
    # ### end Alembic commands ###
